name: Tests and Lint

on: [push, pull_request]

jobs:
  test_lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      # Setup Runner with node
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      # Run all CI actions
    - name: npm install
      run: npm ci
    - name: npm run test
      run: npm run test
    - name: npm run lint
      run: npm run lint
